
export const qizes = {
 nonu:[
  ["Which word is a common noun?", "Africa", "Toyota", "Teacher", "Sunday", "Teacher"],
  ["Which of the following is a proper noun?", "Country", "River", "Amazon", "Animal", "Amazon"],
  ["Identify the abstract noun:", "Car", "Happiness", "Table", "Chair", "Happiness"],
  ["What type of noun is the word 'crowd'?","Collective", "Abstract","Proper", "Countable","Collective"],
  ["Which of the following is a countable noun?", "Water", "Sugar", "Apple", "Milk", "Apple"]
  ["Which of the following is an abstract noun?", "Teacher", "Kindness", "Table", "Lion", "Kindness"],
  ["Identify the collective noun in the sentence: 'The jury gave its verdict.'", "jury", "verdict", "its", "gave", "jury"],
  ["Which noun is uncountable?", "Water", "Apple", "Chair", "Pen", "Water"],
  ["Choose the proper noun:", "city", "car", "Paris", "river", "Paris"],
  ["Which of the following is both countable and uncountable?", "Advice", "Hair", "News", "Information", "Hair"],
  ["Find the abstract noun:", "Hope", "Horse", "Hammer", "House", "Hope"],
  ["Which of these is NOT a common noun?", "Dog", "Love", "Book", "Shakespeare", "Shakespeare"],
  ["Identify the compound noun:", "Sunlight", "Bright", "Light", "Sunny", "Sunlight"],
  ["Choose the material noun:", "Glass", "Clear", "Window", "Transparent", "Glass"],
  ["Which of the following is a proper noun?", "Poet", "Poetry", "Emily Dickinson", "Writing", "Emily Dickinson"],
  ["Pick the collective noun:", "Family", "Father", "Female", "Famous", "Family"],
  ["Identify the abstract noun:", "Justice", "Judge", "Jungle", "Jewel", "Justice"],
  ["Which one is a concrete noun?", "Truth", "Anger", "Chair", "Justice", "Chair"],
  ["What type of noun is 'team'?", "Proper", "Abstract", "Collective", "Material", "Collective"],
  ["Which is a possessive noun?", "Cats", "Cat’s", "Cater", "Cattle", "Cat’s"],
  ["Find the noun functioning as a subject: 'Running is good for health.'", "Running", "good", "health", "for", "Running"],
  ["Which is a gerund noun?", "Eating", "Eat", "Ate", "Eats", "Eating"],
  ["Identify the noun used as object: 'He saw lightning in the sky.'", "He", "saw", "lightning", "in", "lightning"],
  ["Which is the correct plural form of 'goose'?", "Gooses", "Geese", "Goosies", "Goosens", "Geese"],
  ["Which noun is an example of a mass noun?", "Salt", "Bottle", "Ball", "Bag", "Salt"],
  ["Find the noun phrase: 'The tall boy with glasses plays football.'", "boy", "tall boy", "tall boy with glasses", "football", "tall boy with glasses"],
  ["Which of the following nouns is a countable noun?", "Air", "Sugar", "Book", "Milk", "Book"],
  ["Which word is derived from a verb and used as a noun?", "Reading", "Read", "Reads", "Readily", "Reading"],
  ["Which of these is a proper noun used adjectivally?", "American car", "Big car", "Red car", "Fast car", "American car"],
  ["Which of the following is an example of a concrete noun?", "Music", "Noise", "Happiness", "Friend", "Friend"],
  ["Choose the noun that is always singular:", "Scissors", "News", "Pants", "Glasses", "News"],
  ["Which noun has the same form in both singular and plural?", "Sheep", "Cat", "Mouse", "Dog", "Sheep"],
  ["Which of these nouns can be pluralized irregularly?", "Box", "Wolf", "Man", "Toy", "Man"],
  ["Choose the noun used in apposition: 'My friend Tanvir is a doctor.'", "Friend", "Tanvir", "Doctor", "is", "Tanvir"],
  ["Which of these is a verbal noun?", "Running", "Runner", "Ran", "Runned", "Running"],
],pronoun:[
  ["Which one is a personal pronoun?", "She", "That", "Who", "Which", "She"],
  ["Identify the reflexive pronoun:", "Myself", "Him", "Them", "This", "Myself"],
  ["Which is a possessive pronoun?", "Mine", "Me", "Us", "We", "Mine"],
  ["Which one is demonstrative pronoun?", "That", "Hers", "Him", "They", "That"],
  ["Which of the following is a reflexive pronoun?", "Them", "Myself", "Her", "It", "Myself"],
  ["Identify the demonstrative pronoun in the sentence: 'That is amazing!'", "is", "amazing", "That", "sentence", "That"],
  ["Which is a relative pronoun?", "Which", "That", "Who", "All of them", "All of them"],
  ["Which of these sentences uses an indefinite pronoun?", "Somebody knocked at the door.", "He knocked at the door.", "John knocked at the door.", "The man knocked at the door.", "Somebody knocked at the door."],
  ["Choose the intensive pronoun in the sentence: 'I myself completed the entire project.'", "I", "myself", "completed", "entire", "myself"],
  ["Which sentence uses a pronoun incorrectly?", "Each of the boys have done their work.", "Neither of the answers is correct.", "Everyone is present.", "Someone has taken my pen.", "Each of the boys have done their work."],
  ["Which pronoun agrees with the antecedent: 'Everyone must bring ___ own pencil.'", "his", "their", "our", "her", "his"],
  ["Identify the object pronoun:", "They", "She", "Him", "We", "Him"],
  ["Which of the following is a possessive pronoun?", "His", "He", "Him", "Himself", "His"],
  ["What is the correct reflexive form of 'you'?", "Youself", "Yourselves", "Yourself", "Himself", "Yourself"],
  ["Which pronoun is used as the subject in this sentence: 'She went to the market.'", "She", "went", "market", "to", "She"],
  ["Which pronoun correctly completes the sentence: 'The teacher gave the books to you and ___.'", "I", "me", "myself", "mine", "me"],
  ["What type of pronoun is the word 'who' in the sentence: 'Who called last night?'", "Relative", "Demonstrative", "Interrogative", "Indefinite", "Interrogative"],
  ["Which pronoun would replace the noun phrase 'my friend and I' in subject position?", "Them", "We", "Us", "They", "We"],
  ["What is the function of 'it' in the sentence: 'It is raining.'", "Personal", "Dummy subject", "Relative", "Reflexive", "Dummy subject"],
  ["Which sentence uses a reciprocal pronoun?", "They help each other with homework.", "They help themselves.", "He helps him.", "He helps him with his work.", "They help each other with homework."],
  ["Which of the following is NOT an indefinite pronoun?", "Anyone", "Something", "Both", "These", "These"],
  ["Which sentence uses a relative pronoun?", "The man who called you is my uncle.", "The man called.", "He is my uncle.", "That is my pen.", "The man who called you is my uncle."],
  ["Which of the following is an example of an interrogative pronoun?", "What", "This", "That", "Some", "What"],
  ["What kind of pronoun is used in the sentence: 'Each of the students received a prize.'", "Personal", "Reflexive", "Indefinite", "Demonstrative", "Indefinite"],
  ["Choose the correct option: 'Neither of the boys brought ___ books.'", "their", "his", "her", "our", "his"],
  ["Which of these is a compound personal pronoun?", "Itself", "Who", "Those", "Them", "Itself"],
  ["Which sentence shows a correct use of a reflexive pronoun?", "He himself made the decision.", "He made himself the decision.", "He made the decision himself.", "He the decision made himself.", "He himself made the decision."],
  ["Which of these pronouns can be both singular and plural?", "Who", "Which", "All", "That", "All"],
  ["Identify the pronoun in the sentence: 'Nobody knows the answer.'", "Nobody", "knows", "answer", "the", "Nobody"],
  ["What is the correct pronoun to replace 'Jack and Tom'?", "They", "We", "He", "It", "They"],
  ["In the sentence 'This is she', which case is the pronoun 'she' in?", "Object", "Possessive", "Subject", "Reflexive", "Subject"],
  ["Which sentence uses a possessive pronoun correctly?", "This book is mine.", "This book is me.", "This book is myself.", "This book is I.", "This book is mine."],
  ["Choose the pronoun that shows ownership:", "Hers", "Her", "She", "She’s", "Hers"],
  ["Which of the following is a subjective pronoun?", "They", "Them", "Their", "Theirs", "They"]
  ["Which is an interrogative pronoun?", "Who", "He", "They", "Those", "Who"]
],verb:[
  ["Which is an action verb?", "Run", "Is", "Was", "Be", "Run"],
  ["Identify the helping verb:", "Has", "Run", "Play", "Write", "Has"],
  ["Which is a regular verb?", "Talk", "Go", "Be", "Do", "Talk"],
  ["Which one is an irregular verb?", "Went", "Talked", "Played", "Asked", "Went"],
  ["What is the base form of 'went'?", "Go", "Gone", "Goes", "Going", "Go"]
    ["Which sentence uses the past perfect tense correctly?", "He eats before I arrived.", "He had eaten before I arrived.", "He has eaten before I arrived.", "He was eating before I arrive.", "He had eaten before I arrived."],
  ["Identify the finite verb in the sentence: 'Running every morning keeps him healthy.'", "Running", "every", "keeps", "healthy", "keeps"],
  ["Which of the following is an auxiliary verb?", "Run", "Have", "Quickly", "Think", "Have"],
  ["What is the main verb in the sentence: 'She has been working all day.'", "has", "been", "working", "all", "working"],
  ["Which of these is a transitive verb?", "Arrive", "Sleep", "Write", "Go", "Write"],
  ["Which of the following is a verb in subjunctive mood?", "He was late.", "If I were you, I would go.", "She goes home.", "They play football.", "If I were you, I would go."],
  ["Which sentence is in passive voice?", "They painted the house.", "The house was painted by them.", "They are painting the house.", "They will paint the house.", "The house was painted by them."],
  ["What is the infinitive form of the verb in 'She wants to dance'?", "She", "wants", "to", "to dance", "to dance"],
  ["Which of the following is a stative verb?", "Run", "Write", "Know", "Jump", "Know"],
  ["Identify the verb phrase: 'He might have been sleeping.'", "He", "might have been sleeping", "been", "sleeping", "might have been sleeping"],
  ["Which of these is NOT a modal verb?", "Shall", "Must", "Can", "Went", "Went"],
  ["Which sentence demonstrates correct subject-verb agreement?", "The list of items are on the table.", "The team are winning.", "Each of the boys is here.", "The children’s toys is missing.", "Each of the boys is here."],
  ["What is the gerund in this sentence: 'Swimming is good for health.'", "Swimming", "good", "health", "is", "Swimming"],
  ["Which sentence uses a verb incorrectly?", "She don't like pizza.", "He likes ice cream.", "They are playing chess.", "I have finished my work.", "She don't like pizza."],
  ["Which is a verb in future perfect continuous tense?", "Will have been working", "Have worked", "Will working", "Was working", "Will have been working"],
  ["Which of these is a regular verb?", "Swim", "Go", "Play", "Write", "Play"],
  ["Choose the correct irregular past tense verb:", "Buyed", "Bought", "Buy", "Buying", "Bought"],
  ["Identify the intransitive verb:", "Sleep", "Take", "Write", "Fix", "Sleep"],
  ["Which sentence contains a phrasal verb?", "She gave up smoking.", "She gave the book.", "She up the book.", "She smoking gave.", "She gave up smoking."],
  ["Which is the correct past participle of 'lie' (to recline)?", "Lied", "Lay", "Lain", "Laying", "Lain"],
  ["Which form of the verb 'be' fits this sentence: 'I ___ happy today.'", "is", "are", "am", "be", "am"],
  ["What type of verb is 'must'?", "Linking verb", "Action verb", "Modal verb", "Stative verb", "Modal verb"],
  ["Which verb is used incorrectly?", "He do his homework daily.", "She goes to school.", "I saw a movie.", "They have arrived.", "He do his homework daily."],
  ["Which is the past perfect form?", "Had eaten", "Was eating", "Have eaten", "Ate", "Had eaten"],
  ["Which sentence is in the active voice?", "The cake was eaten by the boy.", "The boy ate the cake.", "The cake is being eaten.", "The cake has been eaten.", "The boy ate the cake."],
  ["Which verb correctly completes: 'If she ___ earlier, she wouldn’t be late.'", "left", "leaves", "leave", "leaving", "left"],
  ["Which is the base form of the verb?", "Ran", "Running", "Run", "Runned", "Run"],
  ["Identify the linking verb:", "Tastes", "Runs", "Writes", "Drives", "Tastes"],
  ["Choose the correct sentence in future perfect tense:", "He will have finished the work.", "He will finishing the work.", "He will finishes the work.", "He finished the work.", "He will have finished the work."],
  ["Which sentence uses 'used to' correctly?", "I used to play soccer.", "I use to played soccer.", "I uses to play soccer.", "I using to play soccer.", "I used to play soccer."]  
],
  };

